### ISSUE TITLE
Fatal error during use of the role

### ISSUE THREAD

**Issue by anuragbhatia** [hispanico/ansible-letsencrypt-nginx-revproxy#1]
Getting following error when trying to use this role, any ideas what's wrong: 

`TASK [hispanico.nginx-revproxy : Add Site Config] ***********************************************************************************
fatal: [proxy01]: FAILED! => {"msg": "The conditional check 'item.value.ssl != True | default(True)' failed. The error was: error while evaluating conditional (item.value.ssl != True | default(True)): 'dict object' has no attribute 'ssl'\n\nThe error appears to have been in '.../hispanico.nginx-revproxy/tasks/main.yml': line 47, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add Site Config\n  ^ here\n"}

PLAY RECAP **************************************************************************************************************************
proxy01                    : ok=3    changed=0    unreachable=0    failed=1`

**Comment by hispanico** [comment]
Hi,
this is an old ansible role.
I've merged the let's encrypt feature in this role:
https://galaxy.ansible.com/hispanico/nginx-revproxy
